# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [pull_request]

permissions:
  contents: read

jobs:
  test_unittests:
    name: Test Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest test.py
        
  build_latex:
      name: Build LaTeX
      runs-on: ubuntu-latest
      container: ghcr.io/xu-cheng/texlive-full:latest

      steps:
        - name: Install tools
          run: |
            tlmgr update --self
            tlmgr update --all
            apk add make
            apk add git

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Checkout the repository
          uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: Build all
          run: |
            cd ./project_name
            ./build -v

        - name: Upload artifacts
          uses: actions/upload-artifact@v3
          with:
            name: result
            path: |
              *.pdf
